name: Hourly AI Blog Post and Deploy

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  generate-post:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_post_generated: ${{ steps.commit.outputs.new_post_generated }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Run Python script for post generation
        id: generate
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python generate_article.py
          python generate_article.py
          python generate_article.py
          python generate_article.py
          python generate_article.py

      - name: Commit and push if changes
        id: commit
        run: |
          git config --global user.name "qmwneb946"
          git config --global user.email "qmwneb946@gmail.com"
          
          git pull
          git add -A
          
          if ! git diff-index --quiet HEAD; then
            title_from_output=$(grep '^title=' "$GITHUB_OUTPUT" | cut -d= -f2-)
            git commit -m "feat: AI 自动生成文章 - ${title_from_output}"
            
            git push
            echo "新文章已推送至 main 分支。"
            echo "new_post_generated=true" >> $GITHUB_OUTPUT
          else
            echo "没有文件变动，无需提交。"
            echo "new_post_generated=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: generate-post
    if: needs.generate-post.outputs.new_post_generated == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          git pull
          npm install

      - name: Generate static files
        run: npx hexo g

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: qmwneb946.dpdns.org
